name: "PR: Check mobile minimum version changed"

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  remind-author-to-perform-necessary-checks-for-min-version-change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR HEAD
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
        with:
          fetch-depth: 0

      - name: Check if mobile min version changed
        id: check-mobile-min-version-changed
        run: |
          git fetch origin main
          if git diff --unified=0 origin/main..HEAD -- "src/" | grep -qE "(MINIMUM_MOBILE_APP_VERSION_ANDROID = |MINIMUM_MOBILE_APP_VERSION_IOS =)"; then
            echo "MOBILE_VERSION_CHANGED=true" >> "$GITHUB_OUTPUT"
          fi

      # - name: Mark comment as resolved if prefix is set
      #   uses: marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd # v2.8.0
      #   with:
      #     header: release-strategy
      #     hide: true
      #     hide_classify: RESOLVED

      - name: Post comment on PR if mobile min version changed
        env:
          MOBILE_VERSION_CHANGED: ${{ steps.check-mobile-min-version-changed.MOBILE_VERSION_CHANGED }}
        uses: marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd # v2.8.0
        if: env.MOBILE_VERSION_CHANGED == 'true'
        with:
          header: min-version-changed
          only_create: true
          message: |
            ## 📱 Minimum mobile app version changed
            ### Please make sure to the production app version for android and ios is lower or equal to the new minimum version.

      # - name: Fail the PR check if the prefix isn't set
      # if...
      #   run: |
      #     exit 1
